name: achieve_takehome_test
description: fetch & display assets from coinbase

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4
  get_it: ^4.0.1
  logger: ^0.9.1
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  cached_network_image: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.0
  mockito: 
  environment_config: ^2.2.5

flutter:
  uses-material-design: true
  assets:
    - assets/img/
